/**
 * Starter-template wire format, served as `/templates/<id>.json` and listed in
 * `/templates/index.json`. Declarative plan in centimeters (x right, y down),
 * the same coordinate system as the MCP `build_house` tool. Generated by
 * `npm run templates` from scripts/templates/ — never hand-edited.
 */

export interface TemplateWall {
  key: string
  xStart: number
  yStart: number
  xEnd: number
  yEnd: number
  thickness: number
  height: number
}

interface TemplateRoom {
  name: string
  points: Array<[number, number]>
  floorTextureId: string
}

/** Door or window attached to a wall; `offset` is cm along the wall from its start. */
interface TemplateOpening {
  kind: 'door' | 'window'
  name: string
  wallKey: string
  offset: number
  catalogId: string
  width: number
  depth: number
  height: number
  elevation: number
}

export interface TemplateFurniture {
  name: string
  /** Catalog item supplying the 3D model; absent for plain colored boxes. */
  catalogId?: string
  x: number
  y: number
  angleDeg: number
  width: number
  depth: number
  height: number
  elevation: number
  color?: number
}

export interface TemplatePlan {
  schemaVersion: 1
  id: string
  name: string
  walls: TemplateWall[]
  rooms: TemplateRoom[]
  openings: TemplateOpening[]
  furniture: TemplateFurniture[]
}

/** One entry of `/templates/index.json` — what the marketing site renders. */
export interface TemplateSummary {
  id: string
  name: string
  category: string
  description: string
  /** Outer footprint in cm. */
  widthCm: number
  depthCm: number
  /** Sum of room floor areas in square meters. */
  areaM2: number
  bedrooms: number
  bathrooms: number
  rooms: Array<{ name: string; widthCm: number; depthCm: number; areaM2: number; outdoor?: boolean }>
  furnitureCount: number
  features: string[]
}
